### ISSUE TITLE
Project comparisons

### ISSUE THREAD

**Issue by mottosso** [HolisticCoders/icarus#131]
Hi @holisticcoders!

Good to see more activity in the auto-rigging space, I'm always on the lookout for something new. Would it be possible to add a comparison to other auto-riggers out there? Such as [mgear](http://www.mgear-framework.com/), [rigger.ws](http://rigger.ws/) and [setup machine](http://www.anzovin.com/tsm3), to name a few. Any you're already familiar with. And maybe some example rigs (images or scene files would do good), and mention of target audience and requirements (e.g. scripting knowledge, Python, C++ or just the Maya Node Graph etc).

**Comment by Muream** [comment]
Hi @mottosso!

I've never used any of those autoriggers, I'm a bit familiar with mgear but not enough to make a good comparison.

If you're looking into Master of Puppets as a production tool, I'd go for something else, as it's not mature enough yet.  
At the moment, there are a few bugs here and there, the modules are very basic and and some of them need to be re-written.

I see MOP as tool oriented to experienced TDs who want to have a solid base to build their own rig modules in an autorig that the rigging team will then use.

It's meant to be easily included in any pipeline with the possibility to customize bits of it without touching the source code.
We handle that in two different ways:
- Custom scripts: They are called at various points of the process (pre/post build, pre/post unbuild, pre/post publish, etc) and let you fine tune the MOP's behavior.
There are three levels of custom scripts:
  - Asset: Those scripts just run for the asset they are bound to, it's used to do some custom stuff in the rigs that can't be done via the existing modules
  - Project: Those are run on every asset of a given project, you can specifically target some asset types if you want some scripts to only run on characters and not props for example
  - General: Those scripts are run no matter what. Useful to do stuff like deleting ngSkinTools nodes when publishing a rig or anything that you need across all your different projects.
- The config files. Those are python file that get imported. in there you can define some functions that the MOP will use to do some stuff (naming nodes, creating constraints, etc)
Just like custom scripts, there are multiple levels of configuration:
  - Default: You can't modify this one it's the default config that contains everything that MOP needs to work by default
  - General: The configuration for general stuff that you need on every project
  - Project: only stuff needed for the current project.
The configuration files override the values set in the previous level. meaning that by default if you don't want a behavior from the default config, you can override it in the general or project config.

If you're curious about how that's setup, it's pretty simple: https://github.com/HolisticCoders/master-of-puppets/blob/master/mop/config/__init__.py
You just need to have `mop_general_config.py` and `mop_project_config.py` in your PYTHONPATH for them to be loaded.

That config stuff still needs some love and isn't yet tightly integrated in the autorig but the core building blocs are there.

While writing this, I realized that you can't yet create new rig modules without making them actually part of the source code which is something I want to avoid so we'll have to work on that.

The wiki is also _very_ outdated so don't trust much of what's in there :)

If you have any question or suggestion, I'm all ears!

**Comment by mottosso** [comment]
Hi @Muream, sorry for the delay and thanks for the breakdown! I'll keep an eye on the project for now, and if should happen to stumble upon another auto rigger out there it would be great with a comparison.
