### ISSUE TITLE
Create a list-like operations for Attributes

### ISSUE THREAD

**Issue by Aphosis** [HolisticCoders/icarus#49]
It would allow us to make use of connections again by adding methods like `append` to `ListFields`.

At the moment we cannot use connections because we do not use multi-attributes due to the performance hit, as we can only get or set the list as a whole, but not append a single element for example.
So the current implementation dumps everything to a string and sets the result in the attribute.

For an extensive list of methods to implement, see Python chapter on [Collections Abstract classes](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes).

**Comment by Muream** [comment]
It would be a good idea to compare maya.cmds performance to maya's api
